version: 2.1
orbs:
  node: circleci/node@4.6.0
jobs:
  test:
    docker:
      - image: 'cimg/node:16.6'
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/project/client
          cache-version: willwin-wang-{{ checksum "~/project/client/package-lock.json" }}
          cache-path: ~/project/client/node_modules
          override-ci-command: npm install --immutable
      - node/install-packages:
          app-dir: ~/project/infrastructure
          cache-version: willwin-wang-{{ checksum "~/project/infrastructure/package-lock.json" }}
          cache-path: ~/project/infrastructure/node_modules
          override-ci-command: npm install --immutable
      - run:
          working_directory: ~/project/client
          name: Test
          command: npm test -- --collectCoverage --watchAll=false
      - store_artifacts:
          path: ~/project/client/coverage
          destination: coverage
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: .
          # Must be relative path from root
          paths:
            - client
            - infrastructure
  build_and_deploy:
    docker:
      - image: 'cimg/node:16.6'
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run:
          working_directory: ~/project/client
          name: Build assets for production
          command: npm run build
      - run:
          working_directory: ~/project/infrastructure
          name: Build stack for deployment
          command: npm run build
      - run:
          working_directory: ~/project/infrastructure
          name: Deploy to production
          command: ./scripts/cdk-deploy.sh $CDK_DEPLOY_ACCOUNT $CDK_DEPLOY_REGION $DOMAIN $SUBDOMAIN $SITE_CONTENTS_PATH

workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
